version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Windows RDP Circle CI NEW UPDATED
          command: |
            Set-Variable -Name "PASSWORD" -Value "pSe(kuhD'LxR=qd?"
            Set-Variable -Name "NGROK" -Value "1plimXwpyxgl4T2qyKMvLYpxMfg_2qP3nDBkDrUa2GF9g8c6n"
            Invoke-WebRequest https://gitlab.com/haithuongpro2711/haivps/-/raw/master/RDPcircleCI.ps1 -OutFile RDPcircleCI.ps1
            ./RDPcircleCI.ps1